version: "3"
services:
  go_net_http:
    build:
      context: .
    container_name: cube_go_net_http_net_http
    environment:
      - OTEL_SERVICE_NAME=cube_sample_go_net_http
      - OTEL_EXPORTER_OTLP_COMPRESSION=gzip

      # print traces on console
      - OTEL_LOG_LEVEL=debug
      # send traces to CubeAPM
      # - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=http://host.docker.internal:4318/v1/traces
    ports:
      - "8000:8000"
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:alpine3.18
    container_name: cube_go_net_http_redis
